"""
Django settings

Generated by 'django-admin startproject' using Django 2.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=%3n3%o816q^*3=*3sh@m=^gmcw!lsusbe4jm)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mathfilters',
    'django_prometheus',
    'mfg',
    'sadmin',
    'srv',
    'shp',
    'lrm',
    'tls',
    'tst',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'cims_sfc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': ['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = 'cims_sfc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # ===========================================================================================
    # ===========================================================================================
    # ===========================================================================================

    # ---------- PRD DB BEGIN ------------------------------
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #     'NAME': 'PROJECT_PRD',
    #     'USER': 'postgres',
    #     'PASSWORD': 'password!',
    #     'HOST': '10.12.199.99',
    #     'PORT': '5432',
    # }
    # ---------- PRD DB END --------------------------------

    # ---------- UAT DB BEGIN ------------------------------
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'PROJECT_UAT',
        'USER': 'postgres',
        'PASSWORD': 'password!',
        'HOST': '10.12.199.88',
        'PORT': '5432',
    }
    # ---------- UAT DB END --------------------------------
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York_City'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "live-static", "static-root")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    '/usr/local/lib/python3.6/site-packages/django/contrib/admin/static',
)

LOGIN_URL = 'login'
#LOGIN_REDIRECT_URL = 'home'
LOGIN_REDIRECT_URL = '/accounts/login/'

TEMPLATES_PATH = os.path.join(BASE_DIR, "srv/print/documents/templates")
SECIIT_TEMPLATE_PATH = os.path.join(BASE_DIR, "srv/ftp/doc_templates")


### DOC PATHS ###
GEN_TEMPLATES_PATH_COMMERCIAL_INNVOICE = os.path.join(BASE_DIR, "static/gen_documents/commercial_invoice")

SERVER_IP = 'http://127.0.0.1:9101/'
