CREATE OR REPLACE FUNCTION DFMS_MAZ."FN_GET_MC_CODE"(p_transtype IN VARCHAR2) 
	RETURN sys_refcursor
AS
   	v_res   		sys_refcursor;
BEGIN
	IF p_transtype = 'GET_MC_CODE'
   	THEN
   		OPEN v_res FOR
      		SELECT NVL(MC_CODE, 'N/A') , NVL(MC_DESC, 'N/A') , NVL(SCAN_MODE, 'N/A') , NVL(CATEGORY, 'N/A') , NVL(SCANNABLE, '') FROM WIP_S_MATERIAL_CATEGORY ORDER BY CAST(MC_CODE AS INTEGER);
    END IF;
   
	IF p_transtype = 'GET_SCAN_MODE'
   	THEN
   		OPEN v_res FOR
      	    SELECT SCAN_MODE FROM (SELECT DISTINCT NVL(SCAN_MODE, 'N/A') AS SCAN_MODE FROM WIP_S_MATERIAL_CATEGORY) ORDER BY SCAN_MODE;
    END IF;
   
	IF p_transtype = 'GET_CATEGORY'
   	THEN
   		OPEN v_res FOR
      	    SELECT CATEGORY FROM (SELECT DISTINCT NVL(CATEGORY, 'N/A') AS CATEGORY FROM WIP_S_MATERIAL_CATEGORY) ORDER BY CATEGORY;
    END IF;

   RETURN v_res;
EXCEPTION
   WHEN OTHERS
   THEN
      RETURN v_res;
END FN_GET_MC_CODE;
